services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/fiap-soat-g20/fiap-techchallenge-fase2:latest
    container_name: app.10soat-g18.dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - FAKE_MERCADO_PAGO_URL=http://mockserver:3001/mercadopago/instore/orders/qr
      - FAKE_MERCADO_PAGO_NOTIFICATION_URL=http://app:8080/api/v1/payments/callback
      - MERCADO_PAGO_URL=http://mockserver:3001/mercadopago/instore/orders/qr
      - MERCADO_PAGO_NOTIFICATION_URL=http://app:8080/api/v1/payments/callback
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fastfood_10soat_g18_tc2_network
    restart: unless-stopped

  db:
    image: postgres:17-alpine3.21
    container_name: db.10soat-g18.dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastfood_10soat_g18_tc2
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fastfood_10soat_g18_tc2_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  dbadmin:
    image: dpage/pgadmin4
    container_name: dbadmin.10soat-g18.dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - fastfood_10soat_g18_tc2_network
    restart: unless-stopped

  mockserver:
    # image: mockoon/cli:latest
    build:
      context: .
      dockerfile: Dockerfile.mockserver
    container_name: mockserver.10soat-g18.dev
    # command: ["--port", "3000"]
    # command: ["--data", "https://raw.githubusercontent.com/mockoon/mock-samples/main/samples/generate-mock-data.json", "--port", "3000"]
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:3001/healthCheck || exit 1"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 2
    ports:
      # - "3000:3000"
      - "3001:3001"
    networks:
      - fastfood_10soat_g18_tc2_network
    restart: unless-stopped


volumes:
  db_data:
    driver: local

networks:
  fastfood_10soat_g18_tc2_network:
    driver: bridge
