name: Build Lambda

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2' # Set your Go version

      - name: Build Go Lambda binary
        run: |
          make build

      - name: Zip Lambda binary
        run: |
          make package

      - uses: actions/upload-artifact@v4
        with:
          name: upload-lambda-artifact
          path: ./dist/function.zip